1、库的导入和文件的读入

In [1]:
import os

In [2]:
print(os.getcwd())

C:\Users\Administrator

In [7]:
os.chdir('e:/DS/test')

In [8]:
print(os.getcwd())

e:\DS\test

In [11]:
import pandas as pd

In [22]:
pd.read_csv?

In [24]:
oo=pd.read_csv('./data/olympics.csv',skiprows=4)

2、数据的输入和验证

In [25]:
oo.head(5)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [28]:
type(oo)

pandas.core.frame.DataFrame

In [29]:
oo.City

0         Athens
1         Athens
2         Athens
3         Athens
4         Athens
5         Athens
6         Athens
7         Athens
8         Athens
9         Athens
10        Athens
11        Athens
12        Athens
13        Athens
14        Athens
15        Athens
16        Athens
17        Athens
18        Athens
19        Athens
20        Athens
21        Athens
22        Athens
23        Athens
24        Athens
25        Athens
26        Athens
27        Athens
28        Athens
29        Athens
          ...
29186    Beijing
29187    Beijing
29188    Beijing
29189    Beijing
29190    Beijing
29191    Beijing
29192    Beijing
29193    Beijing
29194    Beijing
29195    Beijing
29196    Beijing
29197    Beijing
29198    Beijing
29199    Beijing
29200    Beijing
29201    Beijing
29202    Beijing
29203    Beijing
29204    Beijing
29205    Beijing
29206    Beijing
29207    Beijing
29208    Beijing
29209    Beijing
29210    Beijing
29211    Beijing
29212    Beijing
29213    Beijing
29214    Beijing
29215    Beijing
Name: City, Length: 29216, dtype: object

In [30]:
type(oo.City)

pandas.core.series.Series

In [32]:
oo.iloc[2]

City                                Athens
Edition                               1896
Sport                             Aquatics
Discipline                        Swimming
Athlete                  DRIVAS, Dimitrios
NOC                                    GRE
Gender                                 Men
Event           100m freestyle for sailors
Event_gender                             M
Medal                               Bronze
Name: 2, dtype: object

In [33]:
oo['City']

0         Athens
1         Athens
2         Athens
3         Athens
4         Athens
5         Athens
6         Athens
7         Athens
8         Athens
9         Athens
10        Athens
11        Athens
12        Athens
13        Athens
14        Athens
15        Athens
16        Athens
17        Athens
18        Athens
19        Athens
20        Athens
21        Athens
22        Athens
23        Athens
24        Athens
25        Athens
26        Athens
27        Athens
28        Athens
29        Athens
          ...
29186    Beijing
29187    Beijing
29188    Beijing
29189    Beijing
29190    Beijing
29191    Beijing
29192    Beijing
29193    Beijing
29194    Beijing
29195    Beijing
29196    Beijing
29197    Beijing
29198    Beijing
29199    Beijing
29200    Beijing
29201    Beijing
29202    Beijing
29203    Beijing
29204    Beijing
29205    Beijing
29206    Beijing
29207    Beijing
29208    Beijing
29209    Beijing
29210    Beijing
29211    Beijing
29212    Beijing
29213    Beijing
29214    Beijing
29215    Beijing
Name: City, Length: 29216, dtype: object

In [43]:
oo[['City','Event']].tail(5)

          City       Event
29211  Beijing   84 - 96kg
29212  Beijing  96 - 120kg
29213  Beijing  96 - 120kg
29214  Beijing  96 - 120kg
29215  Beijing  96 - 120kg

In [45]:
oo.shape

(29216, 10)

In [47]:
oo.shape[0]

29216

In [48]:
oo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
City            29216 non-null object
Edition         29216 non-null int64
Sport           29216 non-null object
Discipline      29216 non-null object
Athlete         29216 non-null object
NOC             29216 non-null object
Gender          29216 non-null object
Event           29216 non-null object
Event_gender    29216 non-null object
Medal           29216 non-null object
dtypes: int64(1), object(9)
memory usage: 2.2+ MB

3、数据的分析:(1)value_counts;(2)sort_values;(3)Boolean indexing

In [49]:
oo.Edition.value_counts()

2008    2042
2000    2015
2004    1998
1996    1859
1992    1705
1988    1546
1984    1459
1980    1387
1976    1305
1920    1298
1972    1185
1968    1031
1964    1010
1952     889
1912     885
1956     885
1924     884
1960     882
1936     875
1948     814
1908     804
1928     710
1932     615
1900     512
1904     470
1896     151
Name: Edition, dtype: int64

In [50]:
oo.Gender.value_counts(ascending=True)

Women     7495
Men      21721
Name: Gender, dtype: int64

In [51]:
oo.Athlete.sort_values()

651                    AABYE, Edgar
2849          AALTONEN, Arvo Ossian
2852          AALTONEN, Arvo Ossian
7716       AALTONEN, Paavo Johannes
7730       AALTONEN, Paavo Johannes
7773       AALTONEN, Paavo Johannes
7709       AALTONEN, Paavo Johannes
8563       AALTONEN, Paavo Johannes
28460              AAMODT, Ragnhild
3436               AANING, Alf Lied
19062         AARDENBURG, Willemien
22769             AARDEWIJN, Pepijn
22267          AARONES, Ann Kristin
3437                  AAS, Karl Jan
2601           AAS, Thomas Valentin
28134              ABAJO, Jose Luis
27691              ABAKUMOVA, Maria
27983           ABALMASAU, Aliaksei
28417                    ABALO, Luc
24202         ABANDA ETONG, Patrice
21538            ABARCA, Jose Maria
27125                 ABAS, Stephen
16390     ABASCAL GARCIA, Alejandro
16806    ABASCAL GOMEZ, Jose Manuel
26049             ABASSOVA, Tamilla
28418                   ABATI, Joel
20477                   ABAY, Peter
6380             ABAY-NEMES, Oszkar
7003                  ABBA, Silvano
24757           ABBAGNALE, Agostino
                    ...
10948                ZYBINA, Galina
9128                 ZYBINA, Galina
8235                 ZYBINA, Galina
15817                ZYCH, Boguslaw
23611                ZYKINA, Olesya
25639                ZYKINA, Olesya
10596              ZÄHRINGER, Klaus
19282               ZÜHLKE, Steffen
18534                ZÜLOW, Andreas
1138                 ZÜRNER, Albert
1939                 ZÜRNER, Albert
15711           ÖRSTED, Hans-Henrik
2691                ÖRTEGREN, Ruben
3745                    ÖRVIG, Erik
3746                    ÖRVIG, Olav
3747                    ÖRVIG, Thor
3868                ÖSTENSEN, Östen
4009                ÖSTENSEN, Östen
3870                ÖSTENSEN, Östen
2730                ÖSTENSEN, Östen
3942                ÖSTENSEN, Östen
3737              ÖSTERVOLD, Henrik
3738           ÖSTERVOLD, Jan Olsen
3739      ÖSTERVOLD, Kristian Olsen
3740           ÖSTERVOLD, Ole Olsen
603                      ÖSTMO, Ole
608                      ÖSTMO, Ole
621                      ÖSTMO, Ole
596                      ÖSTMO, Ole
8051              ÖSTRAND, Per-Olof
Name: Athlete, Length: 29216, dtype: object

In [54]:
oo.sort_values(by=['City','Athlete'])

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
5463,Amsterdam,1928,Gymnastics,Artistic G.,"AGSTERIBBE, Estella",NED,Women,team competition,W,Gold
5146,Amsterdam,1928,Athletics,Athletics,"ALDERMAN, Frederick Pitt",USA,Men,4x400m relay,M,Gold
5512,Amsterdam,1928,Hockey,Hockey,"ALLEN, Richard James",IND,Men,hockey,M,Gold
5076,Amsterdam,1928,Aquatics,Water polo,"AMANN, Max",GER,Men,water polo,M,Gold
5475,Amsterdam,1928,Gymnastics,Artistic G.,"AMBROSETTI, Bianca",ITA,Women,team competition,W,Silver
5109,Amsterdam,1928,Athletics,Athletics,"ANDERSEN, Ove",FIN,Men,3000m steeplechase,M,Bronze
5102,Amsterdam,1928,Athletics,Athletics,"ANDERSON, Stephen",USA,Men,110m hurdles,M,Silver
5368,Amsterdam,1928,Football,Football,"ANDRADE, José",URU,Men,football,M,Gold
5661,Amsterdam,1928,Weightlifting,Weightlifting,"ANDRYSEK, Franz Joseph",AUT,Men,"- 60kg, total (featherweight)",M,Gold
5308,Amsterdam,1928,Fencing,Fencing,"ANGANUZZI, Raul",ARG,Men,foil team,M,Bronze
5638,Amsterdam,1928,Sailing,Sailing,"ANKER, E.",NOR,Men,6m,X,Gold
5639,Amsterdam,1928,Sailing,Sailing,"ANKER, Johan August",NOR,Men,6m,X,Gold
5527,Amsterdam,1928,Hockey,Hockey,"ANKERMAN, Jan Geert",NED,Men,hockey,M,Silver
5340,Amsterdam,1928,Fencing,Fencing,"ANSELMI, Renato",ITA,Men,sabre team,M,Silver
5369,Amsterdam,1928,Football,Football,"ANSELMO, P.",URU,Men,football,M,Gold
5618,Amsterdam,1928,Rowing,Rowing,"ANTHONY, Georges",BEL,Men,pair-oared shell with coxswain (2+),M,Bronze
5277,Amsterdam,1928,Equestrian,Eventing,"ANTONIEWICZ, Michal",POL,Men,team,X,Bronze
5296,Amsterdam,1928,Equestrian,Jumping,"ANTONIEWICZ, Michal",POL,Men,team,X,Silver
5427,Amsterdam,1928,Gymnastics,Artistic G.,"ANTOSIEWIC, Eduard",YUG,Men,team competition,M,Bronze
5201,Amsterdam,1928,Boxing,Boxing,"APELL, Armand",FRA,Men,- 50.8kg (flyweight),M,Silver
5689,Amsterdam,1928,Wrestling,Wrestling Free.,"APPLETON, Lloyd Otto",USA,Men,66 - 72kg (welterweight),M,Silver
5063,Amsterdam,1928,Aquatics,Swimming,"ARAI, Nobuo",JPN,Men,4x200m freestyle relay,M,Silver
5370,Amsterdam,1928,Football,Football,"ARISPE, Pedro",URU,Men,football,M,Gold
5666,Amsterdam,1928,Weightlifting,Weightlifting,"ARNOUT, Fernand",FRA,Men,"60 - 67.5kg, total (lightweight)",M,Bronze
5371,Amsterdam,1928,Football,Football,"ARREMON, Juan Pedro",URU,Men,football,M,Gold
5101,Amsterdam,1928,Athletics,Athletics,"ATKINSON, Sidney",RSA,Men,110m hurdles,M,Gold
5055,Amsterdam,1928,Aquatics,Swimming,"AULT, Garnet Walter",CAN,Men,4x200m freestyle relay,M,Bronze
5221,Amsterdam,1928,Boxing,Boxing,"AVENDANO, Victor",ARG,Men,72.57 - 79.38kg (light-heavyweight),M,Gold
5582,Amsterdam,1928,Rowing,Rowing,"BADCOCK, John Charles",GBR,Men,eight with coxswain (8+),M,Silver
5147,Amsterdam,1928,Athletics,Athletics,"BAIRD, George Hetzel",USA,Men,4x400m relay,M,Gold
...,...,...,...,...,...,...,...,...,...,...
11516,Tokyo,1964,Sailing,Sailing,"WIND, Henning Norgaard",DEN,Men,single-handed dinghy (Finn),M,Bronze
10699,Tokyo,1964,Aquatics,Swimming,"WINDLE, Robert George",AUS,Men,1500m freestyle,M,Gold
10728,Tokyo,1964,Aquatics,Swimming,"WINDLE, Robert George",AUS,Men,4x100m freestyle relay,M,Bronze
10772,Tokyo,1964,Aquatics,Swimming,"WINKEL, Kornelia",NED,Women,4x100m medley relay,W,Silver
11143,Tokyo,1964,Equestrian,Jumping,"WINKLER, Hans Günter",EUA,Men,team,X,Gold
10698,Tokyo,1964,Aquatics,Swimming,"WOOD, Allan",AUS,Men,1500m freestyle,M,Bronze
10713,Tokyo,1964,Aquatics,Swimming,"WOOD, Allan",AUS,Men,400m freestyle,M,Bronze
11354,Tokyo,1964,Hockey,Hockey,"WOOD, Graham",AUS,Men,hockey,M,Bronze
11185,Tokyo,1964,Fencing,Fencing,"WOYDA, Witold",POL,Men,foil team,M,Silver
11307,Tokyo,1964,Gymnastics,Artistic G.,"YAMASHITA, Haruhiro",JPN,Men,team competition,M,Gold
11336,Tokyo,1964,Gymnastics,Artistic G.,"YAMASHITA, Haruhiro",JPN,Men,vault,M,Gold
11637,Tokyo,1964,Wrestling,Wrestling Free.,"YOSHIDA, Yoshikatsu",JPN,Men,- 52kg (flyweight),M,Gold
11531,Tokyo,1964,Shooting,Shooting,"YOSHIKAWA, Yoshihisa",JPN,Men,50m pistol (60 shots),M,Bronze
11206,Tokyo,1964,Fencing,Fencing,"ZABLOCKI, Wojciech",POL,Men,sabre team,M,Bronze
11384,Tokyo,1964,Hockey,Hockey,"ZAFAR, Hayat",PAK,Men,hockey,M,Silver
11385,Tokyo,1964,Hockey,Hockey,"ZAKA, Uddin",PAK,Men,hockey,M,Silver
11046,Tokyo,1964,Canoe / Kayak,Canoe / Kayak F,"ZANDER, Holger",EUA,Men,K-2 1000m (kayak double),M,Bronze
11068,Tokyo,1964,Canoe / Kayak,Canoe / Kayak F,"ZANDER, Holger",EUA,Men,K-4 1000m (kayak four),M,Silver
11070,Tokyo,1964,Cycling,Cycling Road,"ZANIN, Mario",ITA,Men,individual road race,M,Gold
11628,Tokyo,1964,Weightlifting,Weightlifting,"ZDRAZILA, Hans",TCH,Men,"67.5 - 75kg, total (middleweight)",M,Gold
11619,Tokyo,1964,Weightlifting,Weightlifting,"ZHABOTINSKY, Leonid",URS,Men,"+ 90kg, total (heavyweight)",M,Gold
11180,Tokyo,1964,Fencing,Fencing,"ZHDANOVICH, Viktor",URS,Men,foil team,M,Gold
10866,Tokyo,1964,Athletics,Athletics,"ZIELINSKI, Andrzej",POL,Men,4x100m relay,M,Silver
11624,Tokyo,1964,Weightlifting,Weightlifting,"ZIELINSKI, Marian",POL,Men,"60 - 67.5kg, total (lightweight)",M,Bronze
11054,Tokyo,1964,Canoe / Kayak,Canoe / Kayak F,"ZIMMERMANN, Annemarie",EUA,Women,K-2 500m (kayak double),W,Gold
11443,Tokyo,1964,Rowing,Rowing,"ZIMONYI, Robert",USA,Men,eight with coxswain (8+),M,Gold
11079,Tokyo,1964,Cycling,Cycling Road,"ZOET, Hubertus Balthazar",NED,Men,team time trial,M,Gold
10917,Tokyo,1964,Athletics,Athletics,"ZSIVOTZKY, Gyula",HUN,Men,hammer throw,M,Silver
11207,Tokyo,1964,Fencing,Fencing,"ZUB, Ryszard",POL,Men,sabre team,M,Bronze
10948,Tokyo,1964,Athletics,Athletics,"ZYBINA, Galina",URS,Women,shot put,W,Bronze

In [55]:
oo.Medal=='Gold'

0         True
1        False
2        False
3         True
4        False
5        False
6         True
7        False
8        False
9         True
10       False
11       False
12       False
13        True
14       False
15        True
16       False
17       False
18        True
19       False
20       False
21        True
22       False
23       False
24        True
25       False
26       False
27        True
28       False
29        True
         ...
29186    False
29187     True
29188    False
29189    False
29190    False
29191     True
29192    False
29193    False
29194    False
29195     True
29196    False
29197    False
29198    False
29199     True
29200    False
29201    False
29202    False
29203     True
29204    False
29205    False
29206     True
29207    False
29208    False
29209    False
29210     True
29211    False
29212    False
29213    False
29214     True
29215    False
Name: Medal, Length: 29216, dtype: bool

In [56]:
oo[oo.Medal=='Gold']

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
33,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold
36,Athens,1896,Athletics,Athletics,"LOUIS, Spyridon",GRE,Men,marathon,M,Gold
40,Athens,1896,Athletics,Athletics,"HOYT, William Welles",USA,Men,pole vault,M,Gold
43,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,shot put,M,Gold
46,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
49,Athens,1896,Cycling,Cycling Road,"KONSTANTINIDIS, Aristidis",GRE,Men,individual road race,M,Gold
51,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
54,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,10km,M,Gold
56,Athens,1896,Cycling,Cycling Track,"SCHMAL, Adolf",AUT,Men,12-hour race,M,Gold
59,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,1km time trial,M,Gold
62,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,Sprint indivual,M,Gold
65,Athens,1896,Fencing,Fencing,"GRAVELOTTE, Eugène-Henri",FRA,Men,foil individual,M,Gold
67,Athens,1896,Fencing,Fencing,"PYRGOS, Leonidas",GRE,Men,"foil, masters",M,Gold
70,Athens,1896,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,sabre individual,M,Gold
72,Athens,1896,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,horizontal bar,M,Gold
74,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,parallel bars,M,Gold
76,Athens,1896,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,pommel horse,M,Gold
79,Athens,1896,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,rings,M,Gold
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29110,Beijing,2008,Weightlifting,Weightlifting,"ARAMNAU, Andrei",BLR,Men,105kg,M,Gold
29113,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Xiexia",CHN,Women,48kg,W,Gold
29116,Beijing,2008,Weightlifting,Weightlifting,"JAROENRATTANATARAKOON, Prapawadee",THA,Women,53kg,W,Gold
29119,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Yanqing",CHN,Women,58kg,W,Gold
29122,Beijing,2008,Weightlifting,Weightlifting,"ZHANG, Xiangxiang",CHN,Men,62kg,M,Gold
29125,Beijing,2008,Weightlifting,Weightlifting,"PAK, Hyon Suk",PRK,Women,63kg,W,Gold
29128,Beijing,2008,Weightlifting,Weightlifting,"LIAO, Hui",CHN,Men,69kg,M,Gold
29131,Beijing,2008,Weightlifting,Weightlifting,"LIU, Chunhong",CHN,Women,69kg,W,Gold
29134,Beijing,2008,Weightlifting,Weightlifting,"CAO, Lei",CHN,Women,75kg,W,Gold
29137,Beijing,2008,Weightlifting,Weightlifting,"SA, Jaehyouk",KOR,Men,77kg,M,Gold
29140,Beijing,2008,Weightlifting,Weightlifting,"LU, Yong",CHN,Men,85kg,M,Gold
29143,Beijing,2008,Weightlifting,Weightlifting,"ILIN, Ilya",KAZ,Men,94kg,M,Gold
29147,Beijing,2008,Wrestling,Wrestling Free.,"HUYNH, Carol",CAN,Women,- 48kg,W,Gold
29151,Beijing,2008,Wrestling,Wrestling Free.,"CEJUDO, Henry",USA,Men,- 55kg,M,Gold
29155,Beijing,2008,Wrestling,Wrestling Free.,"YOSHIDA, Saori",JPN,Women,48 - 55kg,W,Gold
29159,Beijing,2008,Wrestling,Wrestling Free.,"BATIROV, Mavlet",RUS,Men,55 - 60kg,M,Gold
29163,Beijing,2008,Wrestling,Wrestling Free.,"ICHO, Kaori",JPN,Women,55 - 63kg,W,Gold
29167,Beijing,2008,Wrestling,Wrestling Free.,"SAHIN, Ramazan",TUR,Men,60 - 66kg,M,Gold
29171,Beijing,2008,Wrestling,Wrestling Free.,"WANG, Jiao",CHN,Women,63 - 72kg,W,Gold
29175,Beijing,2008,Wrestling,Wrestling Free.,"SAYTIEV, Buvaysa",RUS,Men,66 - 74kg,M,Gold
29179,Beijing,2008,Wrestling,Wrestling Free.,"MINDORASHVILI, Revazi",GEO,Men,74 - 84kg,M,Gold
29183,Beijing,2008,Wrestling,Wrestling Free.,"MURADOV, Shirvani",RUS,Men,84 - 96kg,M,Gold
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold